### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ocefpaf** [cedadev/cdat_lite#1]
Hi, the URL http://www-pcmdi.llnl.gov/software-portal/cdat/docs/cdat-license seems to be broken and I am unsure what is the license for `cdat_lite`.

**Comment by ocefpaf** [comment]
Ping.

**Comment by ocefpaf** [comment]
Maybe a picture might help :smile: 

![lic](https://cloud.githubusercontent.com/assets/950575/19512656/50134728-95c3-11e6-9306-42688f776be3.png)

**Comment by agstephens** [comment]
Hi @ocefpaf, this UV-CDAT licence is appropriate:

 https://github.com/UV-CDAT/uvcdat/blob/master/LICENSE

**Comment by agstephens** [comment]
Hi @ocefpaf, Dean at PCMDI also sent this reply:

For UV-CDAT you want to take a look at these:
* http://uvcdat.llnl.gov/pdf/uv-cdat-corporate-contributor-agreement.pdf
* http://uvcdat.llnl.gov/pdf/uv-cdat-individual-contributor-agreement.pdf
* http://uvcdat.llnl.gov/governance.html

**Comment by ocefpaf** [comment]
Thanks! Those are helpful. I am packaging `cdat_lite` and I want to be sure the proper license gets propagated with the package.
