### ISSUE TITLE
Incompatible with numpy>=1.9

### ISSUE THREAD

**Issue by aidanheerdegen** [cedadev/cdat_lite#2]
The use of [oldnumeric in ncml.py](https://github.com/cedadev/cdat_lite/blob/master/Packages/ncml/Lib/ncml.py#L7) renders cdat_lite incompatible with any version of numpy>=1.9

https://docs.scipy.org/doc/numpy/reference/routines.oldnumeric.html

https://bitbucket.org/khinsen/scientificpython/issues/13

**Comment by alaniwi** [comment]
Sorry that we did not reply to this issue at the time. We are discontinuing support for this package. If you still require use of CDAT please see https://github.com/CDAT/cdat/wiki/install
